<?php

namespace App\Filament\Resources\PreventiveMaintenanceLogs;

use App\Filament\Concerns\HasCompactTableColumns;
use App\Filament\Resources\JobOrders\JobOrderResource;
use App\Filament\Resources\PreventiveMaintenanceLogs\Pages\ListPreventiveMaintenanceLogs;
use App\Filament\Resources\PreventiveMaintenanceLogs\Pages\ViewPreventiveMaintenanceLog;
use App\Filament\Resources\TicketResource;
use App\Models\PreventiveMaintenanceLog;
use App\PreventiveMaintenanceLogStatus;
use Filament\Actions\ViewAction;
use Filament\Forms\Components\DatePicker;
use Filament\Infolists\Components\TextEntry;
use Filament\Resources\Resource;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

class PreventiveMaintenanceLogResource extends Resource
{
    use HasCompactTableColumns;

    protected static ?string $model = PreventiveMaintenanceLog::class;

    protected static string|\BackedEnum|null $navigationIcon = 'heroicon-o-document-text';

    protected static string|\UnitEnum|null $navigationGroup = 'Asset Management';

    protected static ?string $navigationLabel = 'Preventive Maintenance Logs';

    public static function infolist(Schema $schema): Schema
    {
        return $schema->components([
            Section::make('Generated Work')->schema([
                TextEntry::make('schedule.title')->label('Schedule'),
                TextEntry::make('schedule.inventoryItem.name')->label('Asset'),
                TextEntry::make('schedule.inventoryItemSerialNumber.serial_number')->label('Serial Number'),
                TextEntry::make('generated_at')->dateTime(),
                TextEntry::make('status')->badge()
                    ->formatStateUsing(fn (PreventiveMaintenanceLogStatus $state): string => $state->label())
                    ->color(fn (PreventiveMaintenanceLogStatus $state): string => $state->color()),
                TextEntry::make('completed_at')->dateTime(),
                TextEntry::make('ticket.id')->label('Ticket')->placeholder('None'),
                TextEntry::make('jobOrder.id')->label('Job Order')->placeholder('None'),
                TextEntry::make('schedule.creator.name')->label('Generated By'),
                TextEntry::make('remarks')->columnSpanFull()->placeholder('No remarks'),
            ])->columns(2),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                static::compactTextColumn(TextColumn::make('schedule.title'), 34)->label('Schedule')->searchable()->sortable(),
                static::compactTextColumn(TextColumn::make('schedule.inventoryItem.name'), 30)->label('Asset')->searchable(),
                static::compactTextColumn(TextColumn::make('schedule.inventoryItemSerialNumber.serial_number'), 24)->label('Serial Number'),
                TextColumn::make('generated_at')->label('Generated Date')->dateTime()->sortable(),
                TextColumn::make('ticket.id')->label('Ticket')->url(fn (PreventiveMaintenanceLog $record): ?string => $record->ticket ? TicketResource::getUrl('view', ['record' => $record->ticket]) : null),
                TextColumn::make('jobOrder.id')->label('Job Order')->url(fn (PreventiveMaintenanceLog $record): ?string => $record->jobOrder ? JobOrderResource::getUrl('view', ['record' => $record->jobOrder]) : null),
                TextColumn::make('status')->badge()
                    ->formatStateUsing(fn (PreventiveMaintenanceLogStatus $state): string => $state->label())
                    ->color(fn (PreventiveMaintenanceLogStatus $state): string => $state->color()),
                TextColumn::make('completed_at')->label('Completed Date')->dateTime()->sortable(),
                static::compactTextColumn(TextColumn::make('schedule.creator.name'), 28)->label('Generated By'),
            ])
            ->defaultSort('generated_at', 'desc')
            ->filters([
                SelectFilter::make('status')->options(PreventiveMaintenanceLogStatus::options())->multiple(),
                SelectFilter::make('asset')->relationship('schedule.inventoryItem', 'name')->searchable()->preload(),
                SelectFilter::make('department')->relationship('schedule.department', 'name')->searchable()->preload(),
                Filter::make('generated_date')->form([
                    DatePicker::make('from'),
                    DatePicker::make('until'),
                ])->query(fn (Builder $query, array $data): Builder => $query
                    ->when($data['from'] ?? null, fn (Builder $query, string $date): Builder => $query->whereDate('generated_at', '>=', $date))
                    ->when($data['until'] ?? null, fn (Builder $query, string $date): Builder => $query->whereDate('generated_at', '<=', $date))),
            ])
            ->recordActions([ViewAction::make()]);
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()
            ->whereHas('schedule', fn (Builder $query): Builder => $query->where('department_id', filament()->getTenant()?->getKey()))
            ->with(['schedule.inventoryItem', 'schedule.inventoryItemSerialNumber', 'schedule.creator', 'ticket', 'jobOrder']);
    }

    public static function getPages(): array
    {
        return [
            'index' => ListPreventiveMaintenanceLogs::route('/'),
            'view' => ViewPreventiveMaintenanceLog::route('/{record}'),
        ];
    }

    public static function canViewAny(): bool
    {
        return auth()->user()?->hasAnyRole(['super_admin', 'admin', 'technical_support']) ?? false;
    }

    public static function canCreate(): bool
    {
        return false;
    }

    public static function canEdit($record): bool
    {
        return false;
    }

    public static function canDelete($record): bool
    {
        return false;
    }
}
