<?php

namespace App;

use App\Models\JobOrder;
use App\Models\User;
use Carbon\CarbonInterface;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Response;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

class JobOrderPdfReport
{
    public static function query(array $filters, User $user): Builder
    {
        $departmentId = static::departmentId($filters['department_id'] ?? null, $user);

        return JobOrder::query()->with(['requestor', 'assignedUser', 'inventoryItem', 'inventoryItemSerialNumber.location', 'department'])
            ->when($departmentId, fn (Builder $query, int $id): Builder => $query->where('department_id', $id))
            ->when($filters['status'] ?? null, fn (Builder $query, mixed $value): Builder => $query->whereIn('status', (array) $value))
            ->when($filters['priority'] ?? null, fn (Builder $query, mixed $value): Builder => $query->whereIn('priority', (array) $value))
            ->when($filters['assigned_to_user_id'] ?? null, fn (Builder $query, mixed $id): Builder => $query->where('assigned_to_user_id', $id))
            ->when($filters['inventory_item_id'] ?? null, fn (Builder $query, mixed $id): Builder => $query->where('inventory_item_id', $id))
            ->when($filters['location_id'] ?? null, fn (Builder $query, mixed $id): Builder => $query->where(fn (Builder $query): Builder => $query->whereHas('inventoryItemSerialNumber', fn (Builder $query): Builder => $query->where('location_id', $id))->orWhereHas('inventoryItem', fn (Builder $query): Builder => $query->where('location_id', $id))))
            ->when(static::date($filters['created_from'] ?? null, false), fn (Builder $query, CarbonInterface $date): Builder => $query->where('created_at', '>=', $date))
            ->when(static::date($filters['created_until'] ?? null, true), fn (Builder $query, CarbonInterface $date): Builder => $query->where('created_at', '<=', $date))
            ->latest();
    }

    public static function response(array $filters, User $user): Response
    {
        $orders = static::query($filters, $user)->get();
        $lines = ['Job Order Report', 'Generated: '.now()->format('Y-m-d H:i'), "Generated by: {$user->name}", "Rows: {$orders->count()}", '', str_pad('ID', 6).str_pad('Status', 14).str_pad('Priority', 11).str_pad('Assigned', 24).str_pad('Asset', 28).'Subject', str_repeat('-', 116)];

        foreach ($orders as $order) {
            $lines[] = str_pad((string) $order->id, 6).str_pad($order->status->label(), 14).str_pad(Str::headline($order->priority), 11).str_pad(Str::limit($order->assignedUser?->name ?? 'Unassigned', 22, ''), 24).str_pad(Str::limit($order->inventoryItem?->name ?? '-', 26, ''), 28).Str::limit($order->subject, 36, '');
        }

        return response(TicketPdfReport::pdfContent($lines), 200, ['Content-Type' => 'application/pdf', 'Content-Disposition' => 'inline; filename=job-order-report-'.now()->format('Y-m-d-His').'.pdf']);
    }

    private static function departmentId(mixed $value, User $user): ?int
    {
        if ($user->hasRole('super_admin') && $value === 'all') {
            return null;
        }
        $requested = filled($value) && $value !== 'all' ? (int) $value : null;
        if ($user->hasRole('super_admin')) {
            return $requested;
        }
        if ($requested && $user->departments()->whereKey($requested)->exists()) {
            return $requested;
        }

        return $user->department_id ?? $user->departments()->value('department.id') ?? 0;
    }

    private static function date(mixed $value, bool $end): ?CarbonInterface
    {
        if (blank($value)) {
            return null;
        }

        return $end ? Carbon::parse($value)->endOfDay() : Carbon::parse($value)->startOfDay();
    }
}
