<?php

namespace App;

use App\Models\InventoryItemSerialNumber;
use App\Models\PreventiveMaintenanceAssetCheck;
use App\Models\PreventiveMaintenanceSchedule;
use App\Models\User;
use Carbon\CarbonInterface;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Response;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

class PreventiveMaintenancePdfReport
{
    public static function query(array $filters, User $user): Builder
    {
        return PreventiveMaintenanceAssetCheck::query()->with(['session.location', 'inspector', 'inventoryItem', 'serialNumber', 'ticket'])
            ->whereHas('session', fn (Builder $query): Builder => $query->where('department_id', static::departmentId($filters['department_id'] ?? null, $user)))
            ->when($filters['location_id'] ?? null, fn (Builder $query, mixed $id): Builder => $query->whereHas('session', fn (Builder $query): Builder => $query->where('location_id', $id)))
            ->when($filters['checked_by'] ?? null, fn (Builder $query, mixed $id): Builder => $query->where('checked_by', $id))
            ->when($filters['status'] ?? null, fn (Builder $query, mixed $status): Builder => $query->whereIn('status', (array) $status))
            ->when($filters['inventory_item_id'] ?? null, fn (Builder $query, mixed $id): Builder => $query->where('inventory_item_id', $id))
            ->when($filters['inventory_item_serial_number_id'] ?? null, fn (Builder $query, mixed $id): Builder => $query->where('inventory_item_serial_number_id', $id))
            ->when(static::date($filters['completed_from'] ?? null, false), fn (Builder $query, CarbonInterface $date): Builder => $query->where('completed_at', '>=', $date))
            ->when(static::date($filters['completed_until'] ?? null, true), fn (Builder $query, CarbonInterface $date): Builder => $query->where('completed_at', '<=', $date))
            ->latest('completed_at');
    }

    public static function metrics(array $filters, User $user): array
    {
        $query = static::query($filters, $user);
        $total = $query->clone()->count();
        $completed = $query->clone()->whereNotIn('status', ['pending', 'in_progress'])->count();
        $departmentId = static::departmentId($filters['department_id'] ?? null, $user);

        return [
            'compliance' => $total === 0 ? 0 : (int) round(($completed / $total) * 100),
            'overdue' => PreventiveMaintenanceSchedule::query()->where('department_id', $departmentId)->where('is_active', true)->where('next_due_at', '<', now())->count(),
            'not_inspected' => InventoryItemSerialNumber::query()->whereHas('inventoryItem', fn (Builder $query): Builder => $query->where('department_id', $departmentId)->where('is_it_asset', true)->where('is_deleted', false))->whereIn('status', ['available', 'assigned', 'in_repair'])->whereDoesntHave('preventiveMaintenanceAssetChecks')->count(),
            'needs_repair' => $query->clone()->where('status', PreventiveMaintenanceAssetCheckStatus::NeedsRepair->value)->count(),
        ];
    }

    public static function response(array $filters, User $user): Response
    {
        $checks = static::query($filters, $user)->get();
        $metrics = static::metrics($filters, $user);
        $lines = ['Preventive Maintenance Report', 'Generated: '.now()->format('Y-m-d H:i'), "Generated by: {$user->name}", 'PMS Compliance: '.$metrics['compliance'].'%', 'Overdue PMS: '.$metrics['overdue'], 'Assets Not Inspected: '.$metrics['not_inspected'], 'Assets Requiring Repair: '.$metrics['needs_repair'], '', str_pad('Date', 17).str_pad('Location', 24).str_pad('Serial', 25).str_pad('Result', 16).'Asset', str_repeat('-', 110)];
        foreach ($checks as $check) {
            $lines[] = str_pad($check->completed_at?->format('Y-m-d H:i') ?? '-', 17).str_pad(Str::limit($check->session->location->name, 22, ''), 24).str_pad(Str::limit($check->serialNumber->serial_number, 23, ''), 25).str_pad($check->status->label(), 16).Str::limit($check->inventoryItem->name, 30, '');
        }

        return response(TicketPdfReport::pdfContent($lines), 200, ['Content-Type' => 'application/pdf', 'Content-Disposition' => 'inline; filename=pms-report-'.now()->format('Y-m-d-His').'.pdf']);
    }

    private static function departmentId(mixed $value, User $user): int
    {
        $requested = filled($value) ? (int) $value : null;
        if ($requested && ($user->hasRole('super_admin') || $user->departments()->whereKey($requested)->exists())) {
            return $requested;
        }

        return $user->department_id ?? $user->departments()->value('department.id') ?? 0;
    }

    private static function date(mixed $value, bool $end): ?CarbonInterface
    {
        if (blank($value)) {
            return null;
        }

        return $end ? Carbon::parse($value)->endOfDay() : Carbon::parse($value)->startOfDay();
    }
}
