<?php

namespace App;

use App\Models\Department;
use App\Models\Ticket;
use App\Models\User;
use Carbon\CarbonInterface;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Response;
use Illuminate\Support\Carbon;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;

class TicketPdfReport
{
    private const ALL_DEPARTMENTS = 'all';

    /**
     * @param  array<string, mixed>  $filters
     * @return Builder<Ticket>
     */
    public static function query(array $filters, User $user): Builder
    {
        $filters = static::normalizeFilters($filters);

        return Ticket::query()
            ->with(['client', 'creator', 'department', 'issue', 'technicalSupportUsers'])
            ->visibleTo($user)
            ->when(
                static::departmentIdFor($filters, $user),
                fn (Builder $query, int $departmentId): Builder => $query->where('department_id', $departmentId),
            )
            ->when($filters['status'], fn (Builder $query, array $statuses): Builder => $query->whereIn('status', $statuses))
            ->when($filters['priority'], fn (Builder $query, array $priorities): Builder => $query->whereIn('priority', $priorities))
            ->when($filters['client_id'], fn (Builder $query, int $clientId): Builder => $query->where('client_id', $clientId))
            ->when(
                $filters['technical_support_user_id'],
                fn (Builder $query, int $technicalSupportUserId): Builder => $query->whereHas(
                    'technicalSupportUsers',
                    fn (Builder $query): Builder => $query->whereKey($technicalSupportUserId),
                ),
            )
            ->when(
                $filters['assignment'] === 'assigned',
                fn (Builder $query): Builder => $query->whereHas('technicalSupportUsers'),
            )
            ->when(
                $filters['assignment'] === 'unassigned',
                fn (Builder $query): Builder => $query->whereDoesntHave('technicalSupportUsers'),
            )
            ->when(
                $filters['created_from'],
                fn (Builder $query, CarbonInterface $createdFrom): Builder => $query->where('created_at', '>=', $createdFrom),
            )
            ->when(
                $filters['created_until'],
                fn (Builder $query, CarbonInterface $createdUntil): Builder => $query->where('created_at', '<=', $createdUntil),
            )
            ->latest('created_at');
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    public static function response(array $filters, User $user): Response
    {
        $filters = static::normalizeFilters($filters);
        $tickets = static::query($filters, $user)->get();
        $content = static::pdfContent(static::lines($tickets, $filters, $user));
        $filename = 'ticket-report-'.now()->format('Y-m-d-His').'.pdf';

        return response($content, 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'inline; filename="'.$filename.'"',
        ]);
    }

    /**
     * @param  array<string, mixed>  $filters
     * @return array{
     *     status: array<int, string>,
     *     priority: array<int, string>,
     *     assignment: ?string,
     *     department_id: ?int,
     *     client_id: ?int,
     *     technical_support_user_id: ?int,
     *     created_from: ?CarbonInterface,
     *     created_until: ?CarbonInterface
     * }
     */
    public static function normalizeFilters(array $filters): array
    {
        return [
            'status' => static::arrayFilter($filters['status'] ?? []),
            'priority' => static::arrayFilter($filters['priority'] ?? []),
            'assignment' => in_array($filters['assignment'] ?? null, ['assigned', 'unassigned'], true)
                ? $filters['assignment']
                : null,
            'department_id' => static::departmentFilter($filters['department_id'] ?? null),
            'client_id' => static::integerFilter($filters['client_id'] ?? null),
            'technical_support_user_id' => static::integerFilter($filters['technical_support_user_id'] ?? null),
            'created_from' => static::dateFilter($filters['created_from'] ?? null, endOfDay: false),
            'created_until' => static::dateFilter($filters['created_until'] ?? null, endOfDay: true),
        ];
    }

    /**
     * @param  Collection<int, Ticket>  $tickets
     * @param  array<string, mixed>  $filters
     * @return array<int, string>
     */
    public static function lines(Collection $tickets, array $filters, User $user): array
    {
        $filters = static::normalizeFilters($filters);
        $lines = [
            'Helpdesk Ticket Report',
            'Generated: '.now()->format('Y-m-d H:i'),
            'Generated by: '.$user->name,
            'Filters: '.static::filterSummary($filters, $user),
            'Rows: '.$tickets->count(),
            '',
            str_pad('ID', 6).str_pad('Created', 17).str_pad('Status', 14).str_pad('Priority', 11).str_pad('Client', 24).str_pad('Support', 24).'Subject',
            str_repeat('-', 116),
        ];

        foreach ($tickets as $ticket) {
            $lines[] = str_pad((string) $ticket->id, 6)
                .str_pad($ticket->created_at?->format('Y-m-d H:i') ?? '-', 17)
                .str_pad(static::statusLabel($ticket), 14)
                .str_pad(Str::headline((string) $ticket->priority), 11)
                .str_pad(static::shortText($ticket->client?->name ?? $ticket->created_ticket ?? '-'), 24)
                .str_pad(static::shortText($ticket->technicalSupportUsers->pluck('name')->join(', ') ?: 'Unassigned'), 24)
                .static::shortText($ticket->subject, 38);
        }

        return $lines;
    }

    /**
     * @param  array<int, string>  $lines
     */
    public static function pdfContent(array $lines): string
    {
        $lineChunks = array_chunk($lines, 44);
        $objects = [
            1 => '<< /Type /Catalog /Pages 2 0 R >>',
            3 => '<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>',
        ];
        $pageIds = [];
        $nextObjectId = 4;

        foreach ($lineChunks as $chunk) {
            $pageId = $nextObjectId++;
            $contentId = $nextObjectId++;
            $pageIds[] = $pageId;
            $stream = static::pageStream($chunk);

            $objects[$pageId] = "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 3 0 R >> >> /Contents {$contentId} 0 R >>";
            $objects[$contentId] = '<< /Length '.strlen($stream)." >>\nstream\n{$stream}\nendstream";
        }

        $objects[2] = '<< /Type /Pages /Kids ['.collect($pageIds)->map(fn (int $id): string => "{$id} 0 R")->join(' ').'] /Count '.count($pageIds).' >>';
        ksort($objects);

        $pdf = "%PDF-1.4\n";
        $offsets = [0 => 0];

        foreach ($objects as $id => $object) {
            $offsets[$id] = strlen($pdf);
            $pdf .= "{$id} 0 obj\n{$object}\nendobj\n";
        }

        $xrefOffset = strlen($pdf);
        $pdf .= "xref\n0 ".(count($objects) + 1)."\n";
        $pdf .= "0000000000 65535 f \n";

        foreach (array_keys($objects) as $id) {
            $pdf .= sprintf("%010d 00000 n \n", $offsets[$id]);
        }

        $pdf .= "trailer\n<< /Size ".(count($objects) + 1)." /Root 1 0 R >>\n";
        $pdf .= "startxref\n{$xrefOffset}\n%%EOF";

        return $pdf;
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    protected static function departmentIdFor(array $filters, User $user): ?int
    {
        $departmentId = static::integerFilter($filters['department_id'] ?? null);

        if (! $departmentId) {
            if (static::canReportAcrossDepartments($user)) {
                return null;
            }

            return $user->department_id
                ?? $user->departments()->value('department.id')
                ?? 0;
        }

        if (static::canReportAcrossDepartments($user) || $user->departments()->whereKey($departmentId)->exists()) {
            return $departmentId;
        }

        return $user->department_id
            ?? $user->departments()->value('department.id')
            ?? 0;
    }

    protected static function pageStream(array $lines): string
    {
        $escapedLines = collect($lines)
            ->map(fn (string $line): string => '('.static::escapePdfText($line).') Tj T*')
            ->join("\n");

        return "BT\n/F1 9 Tf\n12 TL\n36 560 Td\n{$escapedLines}\nET";
    }

    protected static function escapePdfText(string $text): string
    {
        return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], Str::ascii($text));
    }

    protected static function shortText(?string $text, int $length = 22): string
    {
        return Str::limit(Str::squish((string) $text), $length, '');
    }

    protected static function statusLabel(Ticket $ticket): string
    {
        return $ticket->status instanceof TicketStatus ? $ticket->status->label() : Str::headline((string) $ticket->status);
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    protected static function filterSummary(array $filters, User $user): string
    {
        $parts = [];

        if ($filters['status']) {
            $parts[] = 'Status '.implode(', ', $filters['status']);
        }

        if ($filters['priority']) {
            $parts[] = 'Priority '.implode(', ', $filters['priority']);
        }

        if ($filters['assignment']) {
            $parts[] = 'Assignment '.$filters['assignment'];
        }

        if ($filters['department_id']) {
            $parts[] = 'Department '.(Department::find($filters['department_id'])?->name ?? $filters['department_id']);
        } elseif (static::canReportAcrossDepartments($user)) {
            $parts[] = 'Department All Departments';
        } elseif ($user->department) {
            $parts[] = 'Department '.$user->department->name;
        }

        if ($filters['created_from']) {
            $parts[] = 'From '.$filters['created_from']->format('Y-m-d');
        }

        if ($filters['created_until']) {
            $parts[] = 'Until '.$filters['created_until']->format('Y-m-d');
        }

        return $parts ? implode('; ', $parts) : 'All visible tickets';
    }

    /**
     * @return array<int, string>
     */
    protected static function arrayFilter(mixed $value): array
    {
        return collect((array) $value)
            ->filter(fn (mixed $item): bool => filled($item))
            ->map(fn (mixed $item): string => (string) $item)
            ->values()
            ->all();
    }

    protected static function integerFilter(mixed $value): ?int
    {
        return filled($value) ? (int) $value : null;
    }

    protected static function departmentFilter(mixed $value): ?int
    {
        if ($value === self::ALL_DEPARTMENTS) {
            return null;
        }

        return static::integerFilter($value);
    }

    protected static function canReportAcrossDepartments(User $user): bool
    {
        return $user->hasAnyRole(['super_admin', 'technical_support']);
    }

    protected static function dateFilter(mixed $value, bool $endOfDay): ?CarbonInterface
    {
        if (blank($value)) {
            return null;
        }

        return $endOfDay
            ? Carbon::parse($value)->endOfDay()
            : Carbon::parse($value)->startOfDay();
    }
}
